language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: hFb3b6TdxCbJ96EbAbmhnK735fc9sO0WtRpDothFDjzxFQiXA9BPkIDCfobOlfBQRFM1gCLcAj6b8oNeWg7DpUvKWrYxYiOZFFNJvD8a8p/UJuPSn3S8nbGlPHRqDNB9GBmfQZsyL7PGVeSo6ZwSSs+9K1Bm/iRRCCVmwIV+EwjMg+6zWsGhF47mBGg2gWCuA/ioZMETnktSN0SNzern1eZVCOkQiPbxkHxrF83ASacirckvSvTC0sIMLbIxH3GGNsPmLds+mNCjoWfWl3IIzidOm/QdPAbyZxrLKPNWJFAOenNp16WcB3+DvOGXe6h0edKcDvmsMF5ELplwr5yIXMTgG08/p3oSXzHxw5cZvGczlzXZlZedC+6e1cPgL1XTlsduY9Ecvr6oKcasNxQK6iULeWXHmMszZ/kS3mhd+7Nvzf5vFYoWAA3toP9ZpkVI975VaiMAad2ugGmvUS6+0o7hCC2Dd4IfXAW8+cb7JLTXumJWBHKf2SixKQr5+f7gJ63TQMZZFu+8s0CjK5SEB8eQFRyXGb1DKGX8C9W7lH33znoHxXGFA6QxUKAlQyfJCLm01lIooIbGjt5EwPFeF9LvrwEOWSB+0/IFn909hSDb9EY5l65XiPMeuzlMOEW0mqOChuJ9busNwZYDFOfWnAEO1ia8xWycKR8svLAGpqE=
  app: nameless-depths-50489
  on:
    repo: jhwheeler/express-blog-mongoose
